logging.level.org.tbk.nostr.template: TRACE

spring.docker.compose:
  enabled: true
  file: ../../docker/regtest/nostr-rs-relay/docker-compose.yml
  #file: ../../docker/regtest/demented/docker-compose.yml
  stop.command: DOWN # STOP is default, DOWN stops and removes containers and networks
  stop.arguments: --volumes
  skip.in-tests: false
